// Weekly challenge definitions — 600 challenges across all tracked stats
// difficulty → bonus points: easy=5, medium=10, hard=20

export const DIFF_POINTS = { easy: 5, medium: 10, hard: 20 }

export const STAT_LABELS = {
  goals: 'Goals', assists: 'Assists', dribbles: 'Dribbles',
  sot: 'Shots on Target', soff: 'Accuracy', possession: 'Possession Won',
  combined: 'Combined Stats', outcome: 'Match Outcome',
  streak: 'Consistency', special: 'Special'
}

// [title, description, stat_category, difficulty]
const _raw = [
  // ── GOALS — EASY ──────────────────────────────────────────────────────────
  ['First Blood','Score at least 1 goal this match','goals','easy'],
  ['Double Strike','Score at least 2 goals this match','goals','easy'],
  ['The Opener','Be the first player to score','goals','easy'],
  ['Second Half Surge','Score a goal in the second half','goals','easy'],
  ['Clinical Finisher','Score with 0 shots off target','goals','easy'],
  ['Goal & Vision','Score 1+ goal and register 1+ assist','goals','easy'],
  ['Dribble & Finish','Complete a dribble then score','goals','easy'],
  ['Match Winner','Score more goals than your opponent and win','goals','easy'],
  ['Tight Win','Score 1+ and keep opponent to 1 goal or fewer','goals','easy'],
  ['First-Half Brace','Score 2 goals before half time','goals','easy'],
  ['Score & Win','Score 2+ and win the match','goals','easy'],
  ['Regain & Score','Win back the ball then score','goals','easy'],
  ['Perfect Shot','Score from your only shot on target (1 SOT = 1 goal)','goals','easy'],
  ['Monthly Opener','Score your first goal of the month','goals','easy'],
  ['Weekly Improvement','Score more goals than you did last week','goals','easy'],
  ['Consecutive Scorer','Score in two consecutive matches','goals','easy'],
  ['Solo Strike','Score 1 goal from 1 shot attempt','goals','easy'],
  ['Brace & Sheet','Score 2 goals and keep a clean sheet','goals','easy'],
  ['Perfect Brace','Score 2 goals from 2 SOT with 0 SOff','goals','easy'],
  ['Assist Then Score','Get an assist then score the next goal','goals','easy'],
  // ── GOALS — MEDIUM ────────────────────────────────────────────────────────
  ['Hat-Trick Hero','Score a hat-trick (3 goals)','goals','medium'],
  ['Four-Goal Fiesta','Score 4 or more goals','goals','medium'],
  ['Hat-Trick Win','Score 3 goals and win by 2+','goals','medium'],
  ['G+A Double','Score 2 goals and provide 2 assists','goals','medium'],
  ['Pristine Hat-Trick','Score 3 goals with 0 shots off target','goals','medium'],
  ['Skill & Goals','Score 3+ goals and complete 3+ dribbles','goals','medium'],
  ['Efficient Four','Score 4 goals from fewer than 5 shots','goals','medium'],
  ['Four & Assist','Score 4 goals and provide 1+ assist','goals','medium'],
  ['Press & Score','Score 3+ goals and win 4+ possessions','goals','medium'],
  ['Four & Sheet','Score 4 goals and keep opponent to 1 or fewer','goals','medium'],
  ['Zero Waste Three','Score 3+ goals with 0 shots off target','goals','medium'],
  ['+3 Margin','Outscore your opponent by exactly 3 goals','goals','medium'],
  ['Double Perfection','Score 2 goals from 2 SOT (100% conversion)','goals','medium'],
  ['Back-to-Back Brace','Score 2+ goals in a second consecutive match','goals','medium'],
  ['Hat-Trick Creator','Score 3 goals and provide 1+ assist','goals','medium'],
  ['Shot-Heavy Brace','Score 2 goals and hit 4+ shots on target','goals','medium'],
  ['Four SOT Match','Score 4 goals and register 4+ SOT','goals','medium'],
  ['Three Press Goals','Score 3+ goals and win 5+ possessions','goals','medium'],
  ['Dribble & Brace','Score 2+ goals and complete 3+ dribbles','goals','medium'],
  ['Season Best Goals','Hit your personal best single-match goal tally','goals','medium'],
  // ── GOALS — HARD ──────────────────────────────────────────────────────────
  ['Five-Star','Score 5 or more goals','goals','hard'],
  ['Six-Shooter','Score 6 or more goals','goals','hard'],
  ['Elite Striker','Score 5 goals from 5 or fewer shots','goals','hard'],
  ['+4 Dominator','Score 4 goals and win by 4+ goals','goals','hard'],
  ['Perfect Conversion','Score from every SOT with min 4 shots and 0 SOff','goals','hard'],
  ['Five & Assists','Score 5+ goals and provide 2+ assists','goals','hard'],
  ['Dribble Four Goals','Score 4 goals and complete 4 dribbles','goals','hard'],
  ['Flawless Hat-Trick','Score a hat-trick with 0 shots off target','goals','hard'],
  ['Seven Heaven','Score 7 or more goals in a single match','goals','hard'],
  ['Clean Four','Score 4+ goals and keep opponent at 0','goals','hard'],
  // ── ASSISTS — EASY ────────────────────────────────────────────────────────
  ['First Assist','Register at least 1 assist','assists','easy'],
  ['Double Vision','Record 2 assists in the match','assists','easy'],
  ['Opening Creator','Assist the opening goal','assists','easy'],
  ['Goal & Assist','Score and register 1+ assist','assists','easy'],
  ['Two Assists Zero Miss','Get 2 assists and keep SOff at 0','assists','easy'],
  ['Vision & Possession','Assist and win 3+ possessions','assists','easy'],
  ['Dribble Creator','Assist and complete 2+ dribbles','assists','easy'],
  ['Match-Winner Assist','Provide the assist on the match-winning goal','assists','easy'],
  ['First of Month','Register your first assist of the month','assists','easy'],
  ['Winning Creator','Record 2 assists in a winning match','assists','easy'],
  ['Assist & SOT','Get 1+ assist and hit 3+ shots on target','assists','easy'],
  ['Two Assists Sheet','Rack up 2 assists and keep opponent to 1 goal','assists','easy'],
  ['Vision & Dribble','Assist and complete 2+ dribbles','assists','easy'],
  ['Key Pass Leader','Register more assists than your opponent','assists','easy'],
  ['Create or Score','Register 3+ combined G+A total','assists','easy'],
  // ── ASSISTS — MEDIUM ──────────────────────────────────────────────────────
  ['Triple Vision','Register 3 assists in the match','assists','medium'],
  ['Four-Time Creator','Record 4 assists in the match','assists','medium'],
  ['Hat-Trick Maker','Rack up 3 assists and also score','assists','medium'],
  ['Pristine Creator','Register 3 assists with 0 shots off target','assists','medium'],
  ['Four-Assist Win','Record 4 assists in a winning cause','assists','medium'],
  ['Assist & Press','Provide 3 assists and win 4+ possessions','assists','medium'],
  ['Dribble Vision+','Provide 3 assists and complete 4+ dribbles','assists','medium'],
  ['Shot Creator','Pick up 3 assists and hit 3+ SOT','assists','medium'],
  ['Sheet Creator','Assist 3 times, keep opponent below 2 goals','assists','medium'],
  ['Four G+A','Score 2+ and assist 2+ in one match','assists','medium'],
  ['Six G+A Combined','Score 3+ and assist 3+ in one match','assists','medium'],
  ['Two G+A Three','Score 3+ and assist 2+ in one match','assists','medium'],
  ['Assist & Win Big','Assist 4 times and win by 3+ goals','assists','medium'],
  ['Season-High Assists','Hit your personal best assist total this match','assists','medium'],
  ['Four G+A Six','Score 3 and assist 3 in one match (G+A: 6)','assists','medium'],
  // ── ASSISTS — HARD ────────────────────────────────────────────────────────
  ['Five-Assist Legend','Register 5 assists in one match','assists','hard'],
  ['Six-Point Game','Provide 4 assists and score 2 goals','assists','hard'],
  ['Perfect Creator','Register 5+ assists with 0 shots off target','assists','hard'],
  ['Vision & Press','Record 4 assists and win all possessions','assists','hard'],
  ['Dribble Vision','Provide 5+ assists and complete 3+ dribbles','assists','hard'],
  ['Five & Score','Rack up 5+ assists and also score','assists','hard'],
  ['Zero Concede Creator','Register 5 assists and keep opponent to 0 goals','assists','hard'],
  ['Generational Creator','Rack up 6 or more assists in a single match','assists','hard'],
  ['Assist Monster','Provide 5 assists in one match from open play','assists','hard'],
  ['Double Hat G+A','Score 2+ and assist 4+ in the same match','assists','hard'],
  // ── DRIBBLES — EASY ───────────────────────────────────────────────────────
  ['First Take-On','Complete at least 1 successful dribble','dribbles','easy'],
  ['Double Take','Complete 2 dribbles in the match','dribbles','easy'],
  ['Dribble & Score','Complete a dribble then score','dribbles','easy'],
  ['First-Half Flair','Beat your man once in the first half','dribbles','easy'],
  ['Dribble Creator Easy','Complete 2+ dribbles and register 1+ assist','dribbles','easy'],
  ['Dribble Winner','Dribble 1+ time and win the match','dribbles','easy'],
  ['Clean Dribble','Complete 1 dribble with 0 shots off target','dribbles','easy'],
  ['Twice & Score','Beat your man 2 times then score','dribbles','easy'],
  ['Dribble & Shoot','Dribble 2+ and hit 3+ SOT','dribbles','easy'],
  ['Dribble & Possess','Complete 1+ dribble and win the possession battle','dribbles','easy'],
  ['Dribble & Brace Easy','Complete 2+ dribbles and score 2+ goals','dribbles','easy'],
  ['Create from Dribble','Dribble 1+ and assist once','dribbles','easy'],
  ['More Dribbles','Complete more dribbles than your opponent','dribbles','easy'],
  ['Double Dribble Win','Complete 2+ dribbles in a winning match','dribbles','easy'],
  ['Second-Half Flair','Beat your man in the second half','dribbles','easy'],
  // ── DRIBBLES — MEDIUM ─────────────────────────────────────────────────────
  ['Triple Take','Complete 3 successful dribbles','dribbles','medium'],
  ['Four-Time Flair','Complete 4 dribbles in the match','dribbles','medium'],
  ['Dribble Goals Medium','Score 2+ goals and complete 3+ dribbles','dribbles','medium'],
  ['Dribble Creator+','Complete 3+ dribbles and assist twice','dribbles','medium'],
  ['Four-Dribble Win','Complete 4+ dribbles and win the match','dribbles','medium'],
  ['Perfect Take-On','Complete 3 dribbles with 0 shots off target','dribbles','medium'],
  ['Dribble & Shoot+','Complete 3+ dribbles and hit 3+ SOT','dribbles','medium'],
  ['Four-Dribble Victory','Beat your man 4 times in a winning match','dribbles','medium'],
  ['Dribble to Score','Beat your man 3 times and score from one','dribbles','medium'],
  ['Four & Create','Complete 4 dribbles and provide 2+ assists','dribbles','medium'],
  ['Dribble & Press','Complete 3 dribbles and win 3+ possessions','dribbles','medium'],
  ['Four Clean Dribble','Complete 4+ dribbles and post 0 shots off target','dribbles','medium'],
  ['Dribble Margin','Complete 3+ dribbles and win by 2+ goals','dribbles','medium'],
  ['Dribble Hat-Trick','Complete 4+ dribbles and score 3 goals','dribbles','medium'],
  ['Dribble Personal Best','Complete 3+ dribbles — personal best for the month','dribbles','medium'],
  // ── DRIBBLES — HARD ───────────────────────────────────────────────────────
  ['Five-Star Dribbler','Complete 5 or more dribbles','dribbles','hard'],
  ['Six-Take King','Complete 6+ dribbles in one match','dribbles','hard'],
  ['Dribble Hat','Dribble 5+ and score a hat-trick','dribbles','hard'],
  ['Five & Create','Beat your man 5+ times and assist twice','dribbles','hard'],
  ['Perfect Five Takes','Complete 5 dribbles from 5 attempts (100% success)','dribbles','hard'],
  ['Five Clean Dribbles','Complete 5+ dribbles with 0 shots off target','dribbles','hard'],
  ['Six-Dribble Win','Complete 6 dribbles and win by 3+ goals','dribbles','hard'],
  ['Complete Winger','Score 2+, assist 2+, and dribble 5+ in one match','dribbles','hard'],
  ['Street King','Achieve 7+ dribbles in a single match','dribbles','hard'],
  ['Dribble Shooter+','Complete 5+ dribbles and register 4+ SOT','dribbles','hard'],
  // ── SHOTS ON TARGET — EASY ────────────────────────────────────────────────
  ['On Target','Hit at least 1 shot on target','sot','easy'],
  ['Double Shot','Hit 2 shots on target','sot','easy'],
  ['Triple Shot','Hit 3 shots on target','sot','easy'],
  ['SOT Leader','Hit more SOT than your opponent','sot','easy'],
  ['Shot & Goal','Hit 2+ SOT and score at least 1 goal','sot','easy'],
  ['Perfect Two SOT','Hit 2 SOT with 0 shots off target','sot','easy'],
  ['Shot & Win','Hit 3+ SOT and win the match','sot','easy'],
  ['Shot Creator SOT','Hit 2+ SOT and register an assist','sot','easy'],
  ['Shot & Dribble','Hit 2+ SOT and complete 2+ dribbles','sot','easy'],
  ['Shot & Press','Hit 3+ SOT and win 3+ possessions','sot','easy'],
  ['Accurate Two','Hit 2+ SOT with 100% on-target rate (0 SOff)','sot','easy'],
  ['Three & Score SOT','Hit 3+ SOT and score 2+ goals','sot','easy'],
  ['Shot Possession','Hit 3+ SOT and win the possession battle','sot','easy'],
  ['Beat SOT','Hit more SOT than your SOff AND score','sot','easy'],
  ['Both Halves SOT','Hit 2+ SOT in each half (4+ total)','sot','easy'],
  // ── SHOTS ON TARGET — MEDIUM ──────────────────────────────────────────────
  ['Four on Target','Hit 4 shots on target','sot','medium'],
  ['Five on Target','Hit 5 shots on target','sot','medium'],
  ['Four & Score','Hit 4+ SOT and score 2+ goals','sot','medium'],
  ['Five & Win','Register 5+ SOT and win the match','sot','medium'],
  ['Nearly Perfect SOT','Hit 4+ SOT with only 1 SOff or fewer','sot','medium'],
  ['Three Goals Five','Hit 5+ SOT and score at least 3 goals','sot','medium'],
  ['Shot & Create+','Register 4+ SOT and provide 1+ assist','sot','medium'],
  ['Dribble & Shoot+','Hit 4+ SOT and complete 3+ dribbles','sot','medium'],
  ['Five & Press','Register 5+ SOT and win 4+ possessions','sot','medium'],
  ['Six Blaster','Register 6+ SOT in the match','sot','medium'],
  ['Clean Sheet SOT','Hit 5+ SOT and your opponent scores 0','sot','medium'],
  ['Five One Miss','Hit 5 SOT with only 1 SOff','sot','medium'],
  ['Four Creates SOT','Register 4+ SOT and provide 2+ assists','sot','medium'],
  ['SOT Season High','Hit your highest SOT total of the season','sot','medium'],
  ['Six & Win SOT','Hit 6 SOT and win the match by 2+','sot','medium'],
  // ── SHOTS ON TARGET — HARD ────────────────────────────────────────────────
  ['Seven Blaster','Hit 7 or more shots on target','sot','hard'],
  ['Eight on Target','Hit 8 SOT in a single match','sot','hard'],
  ['Seven & Score','Register 7+ SOT and score 5+ goals','sot','hard'],
  ['Six & Perfect','Hit 6 SOT with 0 shots off target','sot','hard'],
  ['Seven & Win Big','Hit 7+ SOT and win by 4+ goals','sot','hard'],
  ['Eight & Five Goals','Register 8+ SOT and score 5+ goals','sot','hard'],
  ['Six & Convert','Hit 6 SOT and score from all of them','sot','hard'],
  ['Seven Nearly Perfect','Hit 7+ SOT with only 1 SOff','sot','hard'],
  ['Seven & Create SOT','Register 7+ SOT and provide 2+ assists','sot','hard'],
  ['Nine Blaster','Register 9+ SOT in a single match','sot','hard'],
  // ── SHOTS OFF / ACCURACY — EASY ───────────────────────────────────────────
  ['Zero Miss','Have 0 shots off target this match','soff','easy'],
  ['One Wasted','Hit max 1 shot off target','soff','easy'],
  ['Two Wasted Max','Have at most 2 shots off target','soff','easy'],
  ['Clean Shot Score','Have 0 SOff while scoring 1+ goal','soff','easy'],
  ['Two Goals Zero Miss','Score 2 goals with 0 shots off target','soff','easy'],
  ['Miss Less','Have fewer SOff than your opponent','soff','easy'],
  ['Two-or-Fewer Miss Win','Hit 2 or fewer SOff and win the match','soff','easy'],
  ['Clean Win SOff','Have 0 SOff and win the game','soff','easy'],
  ['Almost Perfect','Miss at most 1 shot (1 SOff max) and score 2+','soff','easy'],
  ['On-Target Majority','Have fewer SOff than SOT this match','soff','easy'],
  // ── SHOTS OFF / ACCURACY — MEDIUM ─────────────────────────────────────────
  ['Zero Miss Four Shot','Finish with 0 SOff and at least 4 SOT','soff','medium'],
  ['Perfect Hat-Trick Acc','Score a hat-trick with 0 missed shots','soff','medium'],
  ['Five Clean Shots','Hit 0 SOff in a match with 5+ SOT','soff','medium'],
  ['Precision Master','Maintain 100% shot accuracy across 4+ shots','soff','medium'],
  ['Three Goals Clean Acc','End with 0 SOff while scoring 3+ goals','soff','medium'],
  ['Four Goals One Miss','Keep SOff to 1 while scoring 4 goals','soff','medium'],
  ['Dual Creator Clean Acc','Score 2, assist 2, and have 0 SOff','soff','medium'],
  ['Five Shots Zero Miss','Post zero wasted shots in a match with 5+ total shots','soff','medium'],
  ['Three Hit Clean Acc','Hit 3 SOT and convert all with 0 SOff','soff','medium'],
  ['Six SOT Near Perfect','Hit 6 SOT with at most 1 SOff','soff','medium'],
  // ── SHOTS OFF / ACCURACY — HARD ───────────────────────────────────────────
  ['Five Goals Zero Miss','Score 5+ goals with 0 shots off target','soff','hard'],
  ['Six Perfect Shots','Hit 6+ SOT with 0 SOff — flawless performance','soff','hard'],
  ['Four Goals Perfect Acc','Score 4+ goals and miss 0 shots entirely','soff','hard'],
  ['Seven Zero','Achieve 7+ SOT and 0 SOff','soff','hard'],
  ['Five from Five Acc','Score 5+ from 5 SOT with no misses','soff','hard'],
  ['Eight Zero Miss','Hit 8 shots with 0 going off target','soff','hard'],
  ['Seven Goals Perfect Acc','Hit 7 SOT and score all 7 — legendary','soff','hard'],
  ['Surgical Precision','Score 6 goals from 6 SOT with 0 SOff','soff','hard'],
  ['Maximum Precision','0 SOff in a 6+ attempt match — absolute clinical','soff','hard'],
  ['Perfect Rout Acc','Score 5+ with 0 SOff and win by 4+','soff','hard'],
  // ── POSSESSION WON — EASY ─────────────────────────────────────────────────
  ['Ball Winner','Win at least 1 possession back','possession','easy'],
  ['Double Winner','Win at least 2 possessions','possession','easy'],
  ['Triple Winner','Win 3 possessions in the match','possession','easy'],
  ['Possession Leader','Win more possessions than your opponent','possession','easy'],
  ['Press & Score','Win 2+ possessions and score a goal','possession','easy'],
  ['Press & Create','Win 3+ possessions and register an assist','possession','easy'],
  ['Press & Dribble','Win 2+ possessions and complete a dribble','possession','easy'],
  ['Second-Half Press','Win 3+ possessions in the second half','possession','easy'],
  ['Press & Shoot','Win 2+ possessions and hit 2+ SOT','possession','easy'],
  ['Press & Win','Win the possession battle and score 2+','possession','easy'],
  ['Three Press Win','Win 3+ possessions and win the match','possession','easy'],
  ['Press Sheet','Claim 2+ possessions and keep opponent at 0','possession','easy'],
  ['Press Dribble Easy','Win 3 possessions and dribble 2+ times','possession','easy'],
  ['Clean Sheet Press','Win 2+ possessions in a clean sheet match','possession','easy'],
  ['Press Both Halves','Win at least 1 possession per half (2+ total)','possession','easy'],
  // ── POSSESSION WON — MEDIUM ───────────────────────────────────────────────
  ['Four-Press Force','Win 4 possessions in the match','possession','medium'],
  ['Five-Press Titan','Win 5 possessions','possession','medium'],
  ['Press & Goals','Win 4+ possessions and score 2+','possession','medium'],
  ['Five & Assist Poss','Claim 5+ possessions and register 1+ assist','possession','medium'],
  ['Four Press Dribble','Win 4 possessions and complete 3 dribbles','possession','medium'],
  ['Five Press Shoot','Win 5+ possessions and hit 4+ SOT','possession','medium'],
  ['Four Press Hat','Win 4 possessions and score 3+ goals','possession','medium'],
  ['Five Press Win','Win 5+ possessions and win match by 2+','possession','medium'],
  ['Four Clean Press','Claim 4+ possessions with 0 shots off target','possession','medium'],
  ['Five & Create Poss','Win 5+ possessions and register 2+ assists','possession','medium'],
  ['Six Press','Claim 6 possessions in a single match','possession','medium'],
  ['Five Hat-Trick Press','Win 5+ possessions and score a hat-trick','possession','medium'],
  ['Four Shoot Press','Claim 4 possessions and hit 4+ SOT','possession','medium'],
  ['Six Press Sheet','Win 6 possessions and keep opponent at 0','possession','medium'],
  ['Five Press Dribble','Claim 5+ possessions in a match with 3+ dribbles','possession','medium'],
  // ── POSSESSION WON — HARD ─────────────────────────────────────────────────
  ['Seven-Press Legend','Win 7 or more possessions','possession','hard'],
  ['Eight-Press Titan','Win 8 possessions in a match','possession','hard'],
  ['Seven Press & Score','Claim 7+ possessions and score 3+ goals','possession','hard'],
  ['Seven & Create Poss','Win 7+ possessions and register 3+ assists','possession','hard'],
  ['Eight Press Win','Dominate with 8+ possessions and win by 3+','possession','hard'],
  ['Seven Dribble Press','Claim 7+ possessions and complete 4+ dribbles','possession','hard'],
  ['Eight Press Score','Win 8+ possessions and score 5+ goals','possession','hard'],
  ['Seven Press Sheet','Claim 7+ possessions and keep opponent to 0','possession','hard'],
  ['Eight Press Shoot','Win 8+ possessions and hit 6+ SOT','possession','hard'],
  ['Nine Dominate','Win 9+ possessions — maximum dominance','possession','hard'],
  // ── COMBINED STATS — EASY ─────────────────────────────────────────────────
  ['G+A Combo','Score 1+ goal AND get 1+ assist','combined','easy'],
  ['Goal & Skill','Score 1+ AND complete 1+ dribble','combined','easy'],
  ['Vision & Heart','Get 1+ assist AND win 2+ possessions','combined','easy'],
  ['Clinical Striker','Score 2+ AND hit 3+ SOT','combined','easy'],
  ['Duel Master','Complete 2+ dribbles AND win 2+ possessions','combined','easy'],
  ['Lethal Finisher','Score 1+ AND have 0 SOff','combined','easy'],
  ['Creative Runner','Get 1+ assist AND complete 2+ dribbles','combined','easy'],
  ['Pressing Threat','Hit 2+ SOT AND win 2+ possessions','combined','easy'],
  ['Complete Attacker','Score 1+ AND win 3+ possessions','combined','easy'],
  ['Assist Artist','Get 2+ assists AND complete 2+ dribbles','combined','easy'],
  ['Scorer Creator','Score 2+ AND get 2+ assists','combined','easy'],
  ['Active Forward','Hit 3+ SOT AND complete 2+ dribbles','combined','easy'],
  ['Disciplined Midfielder','Win 3+ possessions AND have 0 SOff','combined','easy'],
  ['Winning Finisher','Score 1+ AND win match AND 0 SOff','combined','easy'],
  ['Playmaker','Get 2+ assists AND win 3+ possessions','combined','easy'],
  ['Box Threat','Complete 2+ dribbles AND hit 3+ SOT','combined','easy'],
  ['Forward Press','Score 2+ AND win 3+ possessions','combined','easy'],
  ['All-Rounder','Score 1+, get 1+ assist, win 2+ possessions','combined','easy'],
  ['Triple Threat Easy','Score 1+, dribble 2+, win 2+ possessions','combined','easy'],
  ['Clean All-Round','Win 3+ possessions AND score AND get an assist','combined','easy'],
  ['Press & Finish','Score 1, have 0 SOff, win 2+ possessions','combined','easy'],
  ['SOT & Assist','Hit 2+ SOT AND get 1+ assist AND dribble once','combined','easy'],
  ['Dribble Winner Combo','Complete 2+ dribbles AND score 2+ AND win','combined','easy'],
  ['G+A Three Easy','Achieve 3+ combined goals + assists total','combined','easy'],
  ['Press Score Easy','Score AND win 3+ possessions AND hit 2+ SOT','combined','easy'],
  // ── COMBINED STATS — MEDIUM ───────────────────────────────────────────────
  ['Dribble G+A','Score 2+ AND get 2+ assists AND dribble 3+','combined','medium'],
  ['SOT Dominator','Hit 4+ SOT AND win 3+ possessions AND score 2+','combined','medium'],
  ['Clean Hat-Trick Comb','Score 3+ AND get 1+ assist AND 0 SOff','combined','medium'],
  ['Dribble Creator Med','Complete 3+ dribbles AND get 2+ assists AND win','combined','medium'],
  ['Four-Pillar','Win 4+ possessions AND score 3+ AND hit 4+ SOT','combined','medium'],
  ['Six Points','Score 2+ AND assist 2+ AND win 4+ possessions','combined','medium'],
  ['SOT Hat Creator','Hit 4+ SOT AND dribble 3+ AND score 3+','combined','medium'],
  ['Triple Crown','Get 3+ assists AND dribble 3+ AND win match','combined','medium'],
  ['Clean Dominator','Score 3+ AND win 4+ possessions AND 0 SOff','combined','medium'],
  ['Dominant Forward','Hit 5+ SOT AND score 3+ AND win match','combined','medium'],
  ['G+A & Dribble','Score 2+ AND assist 2+ AND dribble 3+','combined','medium'],
  ['Press Creator Med','Win 4+ possessions AND get 3+ assists AND score','combined','medium'],
  ['Dribble SOT Create','Complete 3+ dribbles AND hit 4+ SOT AND get 2+ assists','combined','medium'],
  ['Win by Dribble','Score 3+ AND dribble 2+ AND win by 2+','combined','medium'],
  ['Clean Creator Med','Get 2+ assists AND 0 SOff AND win 3+ possessions','combined','medium'],
  ['Five-Press G+A','Win 5+ possessions AND score 2+ AND get 2+ assists','combined','medium'],
  ['SOT Creator Clean','Hit 4+ SOT AND get 3+ assists AND 0 SOff','combined','medium'],
  ['Three Press Goals+','Score 3+ AND win 5+ possessions AND dribble 2+','combined','medium'],
  ['Dribble & Score Med','Complete 4+ dribbles AND score 2+ AND assist once','combined','medium'],
  ['Hat Four Press','Win 4+ possessions AND score 3+ AND dribble 3+','combined','medium'],
  ['Clinical Four Combo','Hit 4+ SOT AND 0 SOff AND score 3+','combined','medium'],
  ['G+A Win Med','Score 2+ AND assist 3+ AND win by 2+','combined','medium'],
  ['Three Pillars','Complete 3+ dribbles AND hit 4+ SOT AND win 3+ possessions','combined','medium'],
  ['Complete Performance','Score 3+, assist 2+, dribble 2+, win match','combined','medium'],
  ['Clean G+A Med','Score 2+ AND assist 2+ AND 0 SOff AND win','combined','medium'],
  ['Press Hat Dribble','Complete 3+ dribbles AND score 3+ AND win 3+ possessions','combined','medium'],
  ['Five SOT Create','Hit 5+ SOT AND get 2+ assists AND win by 2+','combined','medium'],
  ['Possession Hat','Score 3+ AND win 4+ possessions AND dribble 3+','combined','medium'],
  ['Clean Quad','Get 3+ assists AND 0 SOff AND score 2+ AND dribble 2+','combined','medium'],
  ['G+A Five Press','Win 5+ possessions AND G+A of 4+','combined','medium'],
  // ── COMBINED STATS — HARD ─────────────────────────────────────────────────
  ['Four-Stat Legend','Score 4+ AND assist 3+ AND dribble 4+','combined','hard'],
  ['Six SOT Boss','Hit 6+ SOT AND score 4+ AND win 5+ possessions','combined','hard'],
  ['Clean G+A Hat','Score 3+ AND assist 3+ AND 0 SOff AND win by 3+','combined','hard'],
  ['Fiver Dribble Create','Complete 5+ dribbles AND score 4+ AND assist 3+','combined','hard'],
  ['Six Press SOT Hard','Win 6+ possessions AND score 4+ AND hit 5+ SOT','combined','hard'],
  ['Five Clean Creator','Score 5+ AND assist 2+ AND 0 SOff','combined','hard'],
  ['Dribble Shooter Hard','Complete 4+ dribbles AND hit 6+ SOT AND score 4+','combined','hard'],
  ['Four Assists Five','Get 4+ assists AND score 2+ AND win 5+ possessions','combined','hard'],
  ['Possess & Finish','Score 4+ AND dribble 4+ AND win 5+ possessions','combined','hard'],
  ['Perfect Six SOT','Hit 6+ SOT AND 0 SOff AND score 5+','combined','hard'],
  ['Four Assists Win','Score 4+ AND get 3+ assists AND win by 3+','combined','hard'],
  ['Five Dribble SOT','Complete 5+ dribbles AND hit 5+ SOT AND score 3+','combined','hard'],
  ['Six Press Create','Win 6+ possessions AND get 4+ assists AND score 2+','combined','hard'],
  ['Ultimate Forward','Score 5+, assist once, dribble 3+, win 4+ possessions','combined','hard'],
  ['Seven SOT Clean Comb','Hit 7+ SOT AND score 5+ AND 0 SOff','combined','hard'],
  ['Quad Excellence','Score 3+, assist 3+, dribble 3+, win 5+ possessions','combined','hard'],
  ['Four Zero Combo','Score 4+, assist 3+, dribble 4+, 0 SOff','combined','hard'],
  ['Six Press SOT+','Win 6+ possessions AND hit 6+ SOT AND score 4+','combined','hard'],
  ['Five Everything','Score 5+, assist 3+, dribble 4+, 0 SOff','combined','hard'],
  ['The Masterclass','Score 5+, assist 4+, dribble 4+, 5+ SOT, 0 SOff, 5+ possessions','combined','hard'],
  // ── MATCH OUTCOME — EASY ──────────────────────────────────────────────────
  ['Win It','Win the match','outcome','easy'],
  ['Winner','Win by at least 1 goal','outcome','easy'],
  ['Tight Defence','Keep opponent to 1 goal or fewer','outcome','easy'],
  ['Clean Sheet','Keep a clean sheet (opponent scores 0)','outcome','easy'],
  ['First-Half Lead','Win without conceding in the first half','outcome','easy'],
  ['Exact Two Win','Win by exactly 2 goals','outcome','easy'],
  ['Second-Half Win','Win after being level at half time','outcome','easy'],
  ['Comeback','Win a match after trailing early','outcome','easy'],
  ['Win with Goals','Win the match after scoring 2+','outcome','easy'],
  ['Last Goal Win','Win the match and score the final goal','outcome','easy'],
  ['Clean Win Outcome','Win the match with 0 shots off target','outcome','easy'],
  ['Controlled Win','Keep opponent to max 2 goals in a match you win','outcome','easy'],
  ['Opener & Win','Win the match and score the opening goal','outcome','easy'],
  ['Comeback Win','Win after your opponent scored first','outcome','easy'],
  ['Sheet & Brace','Keep a clean sheet and score 2+ goals','outcome','easy'],
  ['Back-to-Back Win','Win 2 consecutive matches including this one','outcome','easy'],
  ['Win & Shoot','Win the match with 3+ SOT','outcome','easy'],
  ['Win & Zero Miss','Win with 0 shots off target','outcome','easy'],
  ['Sheet Scorer','Keep opponent at 0 while scoring 3+','outcome','easy'],
  ['Three & Sheet Easy','Score 3 goals and keep opponent at 0','outcome','easy'],
  // ── MATCH OUTCOME — MEDIUM ────────────────────────────────────────────────
  ['Win by Three','Win by 3+ goals','outcome','medium'],
  ['Four-Goal Win','Win by 4+ goals','outcome','medium'],
  ['Sheet & Win Big','Keep a clean sheet and win by 2+','outcome','medium'],
  ['Hat-Trick Win Outcome','Score 3 goals and win by 3+','outcome','medium'],
  ['Exact Four','Win by exactly 4 goals','outcome','medium'],
  ['Sheet & Four Goals','Keep a clean sheet and score 4+','outcome','medium'],
  ['Win Clean +3','Win by 3+ with 0 shots off target','outcome','medium'],
  ['Sheet Shoot Medium','Keep clean sheet with 5+ SOT','outcome','medium'],
  ['+3 & Create','Win by 3+ and register 2+ assists','outcome','medium'],
  ['Four & Sheet Med','Score 4+ and keep opponent to 0','outcome','medium'],
  ['+3 Dribble','Win by 3+ and dribble 3+ times','outcome','medium'],
  ['Dribble Win Big','Win by 2+ and complete 4+ dribbles','outcome','medium'],
  ['Sheet SOT Medium','Secure a clean sheet with 4+ SOT','outcome','medium'],
  ['Consecutive +3','Win by 3+ goals in consecutive matches','outcome','medium'],
  ['Four Plus Win','Score 4+ and win by 4+ goals','outcome','medium'],
  ['+4 Clean Win','Win by 4+ goals with 0 shots off target','outcome','medium'],
  ['Sheet Create','Keep a clean sheet and assist twice','outcome','medium'],
  ['Press +3','Win by 3+ and win 4+ possessions','outcome','medium'],
  ['Perfect Clean Sheet','Score 3+, keep 0, 0 SOff in one match','outcome','medium'],
  ['+4 & Create','Win by 4+ and register 3+ assists','outcome','medium'],
  // ── MATCH OUTCOME — HARD ──────────────────────────────────────────────────
  ['+5 Win','Win by 5+ goals','outcome','hard'],
  ['Thrashing','Win by 6+ goals','outcome','hard'],
  ['Five Plus Six','Win by 5+ and score 6+ goals','outcome','hard'],
  ['Perfect +5','Win by 5+ goals with 0 SOff','outcome','hard'],
  ['Six & Clean','Score 6+ and keep opponent to 0 goals','outcome','hard'],
  ['Dribble Rout','Win by 5+ and complete 4+ dribbles','outcome','hard'],
  ['Seven & Sheet','Score 7+ goals with 0 conceded','outcome','hard'],
  ['+6 & Create','Win by 6+ and register 3+ assists','outcome','hard'],
  ['Perfect Sheet SOT','Clean sheet with 6+ SOT and 0 SOff','outcome','hard'],
  ['Press Rout','Win by 5+ and win 6+ possessions','outcome','hard'],
  ['Perfect Seven Goals','Score 7+ goals with 0 shots off target','outcome','hard'],
  ['Perfect Rout','Win by 5+ in a 6+ SOT, 0 SOff match','outcome','hard'],
  ['Back-to-Back Rout','Win by 6+ goals in consecutive matches','outcome','hard'],
  ['Historic Win','Win by 7+ goals','outcome','hard'],
  ['+5 Dribble Clean','Win by 5+ with 4+ dribbles and 0 SOff','outcome','hard'],
  ['Six Assist Rout','Score 6 goals, 0 SOff, and 4+ assists','outcome','hard'],
  ['Press Press Rout','Win by 5+ and win 7+ possessions','outcome','hard'],
  ['Ultimate Clean Out','Score 5+, concede 0, dribble 4+, win 5+ possessions','outcome','hard'],
  ['Legendary Win','Win by 8+ goals','outcome','hard'],
  ['Win From Behind +5','Win by 5+ after trailing at half time','outcome','hard'],
  // ── CONSISTENCY / STREAK — EASY ───────────────────────────────────────────
  ['Better Goals Week','Score more goals than you did last week','streak','easy'],
  ['Better Assists Week','Register more assists than last week','streak','easy'],
  ['Better Dribbles Week','Complete more dribbles than last week','streak','easy'],
  ['Triple Scorer','Score in three consecutive matches','streak','easy'],
  ['Two-Week Assist','Register 1+ assist in two consecutive matches','streak','easy'],
  ['Two-Week Dribble','Complete 2+ dribbles for two consecutive matches','streak','easy'],
  ['Two-Week SOT','Hit 3+ SOT for two consecutive matches','streak','easy'],
  ['Possess Back-to-Back','Win the possession battle 2 weeks in a row','streak','easy'],
  ['Brace Back-to-Back','Score 2+ goals in two consecutive matches','streak','easy'],
  ['P-Index Up','Improve your P-Index vs last week','streak','easy'],
  ['Repeat Win','Win the same type of match you won last week','streak','easy'],
  ['Assist Comeback','Register an assist after scoring 0 last week','streak','easy'],
  ['SOT Best Week','Hit your personal best SOT total this match','streak','easy'],
  ['Two-Week G+A','Register a G+A in two consecutive matches','streak','easy'],
  ['Zero Miss Bounce','Post 0 SOff after having 1+ last week','streak','easy'],
  // ── CONSISTENCY / STREAK — MEDIUM ─────────────────────────────────────────
  ['Five-Match Scorer','Score in 5 consecutive matches','streak','medium'],
  ['Four-Match Creator','Register an assist in 4 consecutive matches','streak','medium'],
  ['Full Improvement','Improve on every stat vs last week','streak','medium'],
  ['Three Zero Miss','Post 0 SOff in 3 consecutive matches','streak','medium'],
  ['Four-Win Streak','Win 4 consecutive matches','streak','medium'],
  ['Four Brace Streak','Score 2+ goals in 4 consecutive matches','streak','medium'],
  ['Three-Week Dribble','Complete 3+ dribbles in 3 consecutive matches','streak','medium'],
  ['Five Possession Wins','Win possession battle in 5 consecutive matches','streak','medium'],
  ['Three High SOT','Hit 4+ SOT in 3 consecutive matches','streak','medium'],
  ['Three G+A','Score and assist in 3 consecutive matches','streak','medium'],
  ['Season G+A Best','Post your best combined G+A total of the season','streak','medium'],
  ['Three Dribble Up','Improve dribbles for the 3rd consecutive week','streak','medium'],
  ['Three Clean Sheets','Win 3 consecutive matches with clean sheets','streak','medium'],
  ['Three Hat Run','Score 3+ in 3 consecutive matches','streak','medium'],
  ['P-Index High','Post your season-high P-Index this match','streak','medium'],
  // ── CONSISTENCY / STREAK — HARD ───────────────────────────────────────────
  ['Five Hat Streak','Score 3+ goals in 5 consecutive matches','streak','hard'],
  ['Seven-Win Streak','Win 7+ consecutive matches','streak','hard'],
  ['Triple Combo Streak','Score, assist, and dribble 3+ in 3 consecutive matches','streak','hard'],
  ['Five Zero Miss','Post 0 SOff in 5 consecutive matches','streak','hard'],
  ['Six Possess Streak','Win possession battle for 6 consecutive matches','streak','hard'],
  ['Five G+A Streak','Score and assist in 5 consecutive matches','streak','hard'],
  ['Four P-Index Up','Improve P-Index for 4 consecutive weeks','streak','hard'],
  ['Five Clean Streak','Win 5 consecutive matches with clean sheets','streak','hard'],
  ['Three Four-Goal Run','Score 4+ goals in 3 consecutive matches','streak','hard'],
  ['Personal Best All','Set a personal best in every single stat in one match','streak','hard'],
  // ── SPECIAL / CREATIVE — EASY ─────────────────────────────────────────────
  ['Jack of All Stats','Register 1+ in goals, assists, dribbles, SOT, and possessions won','special','easy'],
  ['G+A Two Easy','Score 1 goal and assist 1 in the same match','special','easy'],
  ['Win Fewer Shots','Win the match while registering fewer total shots','special','easy'],
  ['Score Less Dribble','Score without dribbling more than your opponent','special','easy'],
  ['Efficient Two Easy','Score 2 goals from just 2 shots on target','special','easy'],
  ['Win the Miss Battle','Win the match with the lower SOff count','special','easy'],
  ['Win & Celebrate','Win match and provide 2+ assists','special','easy'],
  ['Assist Then Win','Get an assist on the game-winning goal','special','easy'],
  ['Dribble No SOff','Win the match with more dribbles than SOff','special','easy'],
  ['Both Contribute','Score a goal and complete a dribble in one match','special','easy'],
  ['Perfect Ratio','Score from all your SOT AND win the possession battle','special','easy'],
  ['Quad Beginner','Score 1+, get 1+ assist, dribble 1+, win 1+ possession','special','easy'],
  ['Goal Every Half','Score at least 2 goals — one in each half','special','easy'],
  ['Perfect First','Win the match while setting a personal best in 1 stat','special','easy'],
  ['G+A Three','Achieve G+A of 3 in a match you also win','special','easy'],
  ['No Waste Win Easy','Win with 0 SOff AND more SOT than opponent','special','easy'],
  ['Dribble to Victory','Complete the most dribbles AND win the match','special','easy'],
  ['No Waste Match','Win with fewer SOff misses than your opponent','special','easy'],
  ['Balanced Threat','Score 2+, hit 2+ SOT, win 2+ possessions','special','easy'],
  ['Comeback Hero Easy','Score after trailing by 1 to draw or win','special','easy'],
  // ── SPECIAL / CREATIVE — MEDIUM ───────────────────────────────────────────
  ['Double G+A Med','Score 2 goals and get 2 assists (G+A: 4)','special','medium'],
  ['Possession vs SOT','Have more possession wins than opponent has SOT','special','medium'],
  ['Perfect Conversion Spc','Score from every shot attempt (all SOT result in goals)','special','medium'],
  ['Triple Dominance','Win possessions, goals, and dribbles all vs opponent','special','medium'],
  ['Pristine Hat-Trick Spc','Score 3 goals from 3 SOT with 0 SOff','special','medium'],
  ['Six-Stat Sweep','Win the match and lead in all 6 stats','special','medium'],
  ['Assist Clean Spc','Get 3+ assists with 0 shots off target','special','medium'],
  ['Five G+A','Achieve a G+A (goals + assists) total of 5+','special','medium'],
  ['Dribble Ratio Spc','Score 3+ while dribbles total > SOff total','special','medium'],
  ['Zero Miss Win Med','Win the match with 0 SOff AND win 3+ possessions','special','medium'],
  ['Perfect Combo','Score 2 from 2 SOT AND win 4 possessions AND get 2 assists','special','medium'],
  ['Six G+A Med','Achieve a G+A total of 6+ in one match','special','medium'],
  ['Double Perfection Spc','Complete 3 dribbles and score 3 from 3 SOT','special','medium'],
  ['Five SOT Zero Win','Win the match with 0 SOff and 5+ SOT','special','medium'],
  ['Clean G+A Four','G+A of 4 with 0 SOff in a winning match','special','medium'],
  ['Duel Sweep Med','Win goals, dribbles, and possessions vs opponent','special','medium'],
  ['G+A Five Zero','G+A of 5 in a match with 0 SOff','special','medium'],
  ['Triple Perfect Spc','Score 3 from 3 SOT with 3 assists and 0 SOff','special','medium'],
  ['Perfect Half','Score 3+ goals and 3+ assists in one match','special','medium'],
  ['Session Pb3','Post a personal best in 3 different stats in one match','special','medium'],
  // ── SPECIAL / CREATIVE — HARD ─────────────────────────────────────────────
  ['Eight G+A','Achieve a G+A total of 8 in one match','special','hard'],
  ['Five Perfect Spc','Score 5 from 5 SOT with 3 assists AND 0 SOff','special','hard'],
  ['Full Sweep Spc','Win all 6 stat categories AND G+A total of 7+','special','hard'],
  ['Zero Five Spc','Have 0 SOff AND score 5+ AND 5+ SOT','special','hard'],
  ['Four Four Combo','Score 4 AND assist 4 in one match (G+A: 8)','special','hard'],
  ['Perfect Match','Win every stat, 0 SOff, score 5+ goals','special','hard'],
  ['Nine G+A','Achieve G+A of 9+ in a single match','special','hard'],
  ['Quintuple Double','Get 3+ in goals, assists, dribbles, SOT, AND possessions','special','hard'],
  ['Triple Hat Spc','Score 3, assist 3, dribble 3, win 3 possessions, 3 SOT, 0 SOff','special','hard'],
  ['Five Stat Perfect','Score 5+, assist 4+, dribble 4+, 6+ SOT, 0 SOff, 5+ possessions','special','hard'],
  ['Rout Sweep Spc','Win by 5+ AND sweep all stats AND score 6+','special','hard'],
  ['Ten G+A','Achieve a G+A of 10 in a single match','special','hard'],
  ['Clean Everything','Clean sheet, 5+ goals, 3+ assists, 5+ SOT, 0 SOff','special','hard'],
  ['Five from Five Spc','Score 5 from 5 shots with 4 assists and 0 SOff','special','hard'],
  ['Sweep Plus','Win all 6 stat categories AND achieve G+A of 8+','special','hard'],
  ['Double Hat Spc','Score 3 goals AND get 3 assists in same match','special','hard'],
  ['Four Perfect Spc','Score 4 from 4 SOT AND dribble 4 AND 0 SOff','special','hard'],
  ['+3 Duel Sweep','Win match by 3+ AND win every duel category','special','hard'],
  ['Seven G+A Press','Achieve G+A of 6 with 5+ possessions won','special','hard'],
  ['Masterclass Spc','Score 5, assist 5, dribble 5, win 5 possessions, 5 SOT, 0 SOff','special','hard'],
  ['Zero SOT Opponent','Win the match with opponent registering 0 SOT','special','hard'],
  ['Four Clear Perfect','Score 4+, opponent 0 SOT, your SOff also 0','special','hard'],
  ['Pure Playmaker','Register 3+ assists with 0 goals and 0 SOff','special','hard'],
  ['Precise Winger Hard','Complete 4 dribbles and get 3 assists with 0 SOff','special','hard'],
  ['Hat Two Assist Spc','Score a hat-trick and provide 2 assists (5-point game)','special','hard'],
  ['G+A10 Sheet','Achieve 10+ combined G+A with 0 SOff and a clean sheet','special','hard'],
  ['Defend & Score Hard','Win possessions AND score 3+ AND keep 0 AND 0 SOff','special','hard'],
  ['Six Stat Perfection','Beat opponent in all 6 stats by at least 2 each','special','hard'],
  ['Complete Footballer','Score 3+, assist 3+, dribble 3+, win 3+ possessions, 3+ SOT, 0 SOff, win by 3+','special','hard'],
  ['Legend Status','Score 4+, assist 4+, dribble 4+, win 6+ possessions, 6+ SOT, 0 SOff','special','hard'],
]

export const CHALLENGES = _raw.map((r, i) => ({
  id: `ch-${String(i + 1).padStart(3, '0')}`,
  title: r[0],
  description: r[1],
  stat: r[2],
  difficulty: r[3],
  points: DIFF_POINTS[r[3]]
}))

export function findChallenge(id) {
  return CHALLENGES.find(c => c.id === id) ?? null
}

export const DIFF_EMOJI = { easy: '🟢', medium: '🟡', hard: '🔴' }
export const DIFF_LABEL = { easy: 'Easy', medium: 'Medium', hard: 'Hard' }
